In [90]:
import numpy as np

In [91]:
a=np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [92]:
mean_a=a.mean(axis=0)
print(mean_a)

[2.  8.4]


In [93]:
a_centered=a-mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [95]:
a_centered_sp=np.dot(a_centered[0:,0],a_centered[0:,1])
n=2
p=a_centered/(n-1)
print(p)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]
